<?php

/**
 * @file
 * Contains alert_scheduler_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function alert_scheduler_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alert_scheduler_api module.
    case 'help.page.alert_scheduler_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the API to access alert messages.') . '</p>';
      return $output;

    default:
  }
}
